# Generated by Django 5.2.6 on 2025-10-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description_resolved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
