# Generated by Django 5.2.6 on 2025-11-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_assigned_to_alter_ticket_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_change_ticket_status', 'Pode alterar o status do próprio ticket')]},
        ),
    ]
