# Generated by Django 5.2.5 on 2025-09-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name_plural': 'Opções'},
        ),
        migrations.CreateModel(
            name='FeedbackPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=3)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.pergunta')),
            ],
            options={
                'db_table': 'feedbacks_perguntas',
            },
        ),
    ]
