# Generated by Django 5.2.5 on 2025-08-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pergunta", models.CharField(max_length=100)),
                (
                    "data_publicacao",
                    models.DateTimeField(verbose_name="Data de publicação"),
                ),
            ],
            options={
                "db_table": "perguntas",
            },
        ),
        migrations.CreateModel(
            name="Opcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_opcao", models.CharField(max_length=100)),
                ("votos", models.IntegerField(default=0)),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enquetes.pergunta",
                    ),
                ),
            ],
            options={
                "db_table": "opcoes",
            },
        ),
    ]
